<a href="https://colab.research.google.com/github/Shivanb1/Data690_ShivaniB/blob/main/Individual_Project_Part_B_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Name: Badinehal Shivani 
### Professor : Dr. Chaojie Wang

In [ ]:
import pandas as pd
import plotly
print('plotly version',plotly.__version__)
import plotly.graph_objects as go
import plotly.express as px
import plotlywidget
import plotly.io as pio

plotly version 5.5.0

In [ ]:
pio.templates.default = "plotly_dark"

In [ ]:
!pip install plotly --upgrade

Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.7.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)

In [ ]:
df = pd.read_csv('/content/wdi_data.csv')
df.head()

,Unnamed: 0,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,0,2015,1.00029,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
1,1,2016,0.99978,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
2,2,2017,0.99990,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
3,3,2018,0.99891,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
4,4,2019,0.99921,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified

In [ ]:
df['Country Code'].unique()

array(['AUS', 'CHN', 'FRA', 'DEU', 'IND', 'JPN', 'KOR', 'PAK', 'USA'],
      dtype=object)

In [ ]:
df['Country Name'].unique()

array(['Australia', 'China', 'France', 'Germany', 'India', 'Japan',
       'Korea, Rep.', 'Pakistan', 'United States'], dtype=object)

In [ ]:
df_new= df.drop(columns=["Unnamed: 0"])
df_new.head()

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
0,2015,1.00029,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
1,2016,0.99978,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
2,2017,0.99990,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
3,2018,0.99891,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
4,2019,0.99921,SE.ENR.PRIM.FM.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified

In [ ]:
df_new.tail(20)

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
368,2018,17.09000,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
369,2019,16.98000,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
370,2015,44.95000,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
371,2016,45.79000,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
372,2017,47.08000,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
373,2018,47.42000,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
374,2019,47.92000,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
375,2018,1.00000,SE.ADT.1524.LT.FM.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
376,2018,0.96964,SE.ADT.1524.LT.FM.ZS,IND,India,South Asia,Lower middle income,IBRD
377,2017,0.83109,SE.ADT.1524.LT.FM.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
378,2018,0.80656,SE.ADT.1524.LT.FM.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
379,2019,0.81759,SE.ADT.1524.LT.FM.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
380,2018,5.90278,SG.TIM.UWRK.MA,CHN,China,East Asia & Pacific,Upper middle income,IBRD
381,2016,3.12500,SG.TIM.UWRK.MA,JPN,Japan,East Asia & Pacific,High income,Not classified
382,2019,4.37500,SG.TIM.UWRK.MA,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
383,2015,9.75000,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
384,2016,9.79167,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
385,2017,9.87500,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
386,2018,9.54167,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
387,2019,9.66667,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified

In [ ]:
df_ind = df_new[df_new['Country Code']== 'IND']
df_ind

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
21,2015,1.11618,SE.ENR.PRIM.FM.ZS,IND,India,South Asia,Lower middle income,IBRD
22,2016,1.16104,SE.ENR.PRIM.FM.ZS,IND,India,South Asia,Lower middle income,IBRD
23,2017,1.14725,SE.ENR.PRIM.FM.ZS,IND,India,South Asia,Lower middle income,IBRD
24,2019,1.01958,SE.ENR.PRIM.FM.ZS,IND,India,South Asia,Lower middle income,IBRD
25,2020,1.01941,SE.ENR.PRIM.FM.ZS,IND,India,South Asia,Lower middle income,IBRD
64,2015,442275.00000,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
65,2016,417596.00000,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
66,2017,395131.00000,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
67,2018,374519.00000,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
68,2019,356238.00000,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
93,2019,50.00000,SG.AGE.RTRE.PL.FE,IND,India,South Asia,Lower middle income,IBRD
94,2020,50.00000,SG.AGE.RTRE.PL.FE,IND,India,South Asia,Lower middle income,IBRD
123,2015,36.46000,SL.EMP.1524.SP.MA.ZS,IND,India,South Asia,Lower middle income,IBRD
124,2016,35.42000,SL.EMP.1524.SP.MA.ZS,IND,India,South Asia,Lower middle income,IBRD
125,2017,34.45000,SL.EMP.1524.SP.MA.ZS,IND,India,South Asia,Lower middle income,IBRD
126,2018,33.48000,SL.EMP.1524.SP.MA.ZS,IND,India,South Asia,Lower middle income,IBRD
127,2019,32.76000,SL.EMP.1524.SP.MA.ZS,IND,India,South Asia,Lower middle income,IBRD
152,2019,50.00000,SG.AGE.RTRE.PL.MA,IND,India,South Asia,Lower middle income,IBRD
153,2020,50.00000,SG.AGE.RTRE.PL.MA,IND,India,South Asia,Lower middle income,IBRD
202,2015,1.00000,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
203,2016,1.00000,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
204,2017,1.00000,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
205,2018,1.00000,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
206,2019,1.00000,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
207,2020,1.00000,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
260,2015,851000.00000,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
261,2016,801578.00000,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
262,2017,756546.00000,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
263,2018,715531.00000,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
264,2019,678728.00000,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
305,2015,408725.00000,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
306,2016,383982.00000,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
307,2017,361415.00000,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
308,2018,341012.00000,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
309,2019,322490.00000,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
350,2015,9.29000,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
351,2016,8.67000,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
352,2017,8.13000,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
353,2018,7.64000,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
354,2019,7.42000,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
376,2018,0.96964,SE.ADT.1524.LT.FM.ZS,IND,India,South Asia,Lower middle income,IBRD

## Calculating the number of infant deaths in india

In [ ]:
df_ind_infant = df_ind.query("indicator in(['SH.DTH.IMRT'])")
df_ind_infant

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
260,2015,851000.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
261,2016,801578.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
262,2017,756546.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
263,2018,715531.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
264,2019,678728.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD

In [ ]:
df_pivot = df_ind_infant.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_pivot

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SH.DTH.IMRT
0,2015,IND,India,South Asia,Lower middle income,IBRD,851000.0
1,2016,IND,India,South Asia,Lower middle income,IBRD,801578.0
2,2017,IND,India,South Asia,Lower middle income,IBRD,756546.0
3,2018,IND,India,South Asia,Lower middle income,IBRD,715531.0
4,2019,IND,India,South Asia,Lower middle income,IBRD,678728.0

In [ ]:
fig = px.bar(
    df_pivot.dropna(),
    x = "Year",
    y = "SH.DTH.IMRT",
    title = "Infant deaths",
    labels = {"SH.DTH.IMRT":"infant male deaths ","SH.DTH.IMRT":"total child deaths"},
    color = "Region",
    hover_name = "Country Name",
    text = "Country Name",
    #size = "SP.POP.TOTL"
)
#fig.update_traces(textposition = "top center")

fig.show()

## Comparing the number of infant deaths between different countries

In [ ]:
df_infants = df_new.query("indicator in(['SH.DTH.IMRT','SH.DTH.IMRT.FE','SH.DTH.IMRT.MA'])")
df_infants

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
44,2015,568.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
45,2016,560.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
46,2017,554.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
47,2018,549.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
48,2019,542.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
...,...,...,...,...,...,...,...,...
325,2015,10105.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
326,2016,9979.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
327,2017,9884.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
328,2018,9787.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
329,2019,9678.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified

In [ ]:
df_pivot = df_ind_infant.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_pivot

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SH.DTH.IMRT
0,2015,IND,India,South Asia,Lower middle income,IBRD,851000.0
1,2016,IND,India,South Asia,Lower middle income,IBRD,801578.0
2,2017,IND,India,South Asia,Lower middle income,IBRD,756546.0
3,2018,IND,India,South Asia,Lower middle income,IBRD,715531.0
4,2019,IND,India,South Asia,Lower middle income,IBRD,678728.0

In [ ]:
fig = px.bar(
    df_pivot.dropna(),
    x = "Year",
    y = "SH.DTH.IMRT",
    title = "Infant deaths",
    labels = {"SH.DTH.IMRT":"infant male deaths ","SH.DTH.IMRT":"total child deaths"},
    color = "Region",
    hover_name = "Country Name",
    text = "Country Name",
    #size = "SP.POP.TOTL"
)
#fig.update_traces(textposition = "top center")

fig.show()

## Comparing the number of infant deaths between different countries

In [ ]:
df_infants = df_new.query("indicator in(['SH.DTH.IMRT','SH.DTH.IMRT.FE','SH.DTH.IMRT.MA'])")
df_infants

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
44,2015,568.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
45,2016,560.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
46,2017,554.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
47,2018,549.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
48,2019,542.0,SH.DTH.IMRT.MA,AUS,Australia,East Asia & Pacific,High income,Not classified
...,...,...,...,...,...,...,...,...
325,2015,10105.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
326,2016,9979.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
327,2017,9884.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
328,2018,9787.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
329,2019,9678.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified

In [ ]:
df_country = df_infants[df_infants["Country Code"].isin(["IND","CHN","PAK","USA"])]
df_country

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
49,2015,90929.0,SH.DTH.IMRT.MA,CHN,China,East Asia & Pacific,Upper middle income,IBRD
50,2016,83166.0,SH.DTH.IMRT.MA,CHN,China,East Asia & Pacific,Upper middle income,IBRD
51,2017,75962.0,SH.DTH.IMRT.MA,CHN,China,East Asia & Pacific,Upper middle income,IBRD
52,2018,69038.0,SH.DTH.IMRT.MA,CHN,China,East Asia & Pacific,Upper middle income,IBRD
53,2019,63096.0,SH.DTH.IMRT.MA,CHN,China,East Asia & Pacific,Upper middle income,IBRD
64,2015,442275.0,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
65,2016,417596.0,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
66,2017,395131.0,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
67,2018,374519.0,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
68,2019,356238.0,SH.DTH.IMRT.MA,IND,India,South Asia,Lower middle income,IBRD
79,2015,200640.0,SH.DTH.IMRT.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
80,2016,198098.0,SH.DTH.IMRT.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
81,2017,195090.0,SH.DTH.IMRT.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
82,2018,191615.0,SH.DTH.IMRT.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
83,2019,187606.0,SH.DTH.IMRT.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
84,2015,12620.0,SH.DTH.IMRT.MA,USA,United States,North America,High income,Not classified
85,2016,12465.0,SH.DTH.IMRT.MA,USA,United States,North America,High income,Not classified
86,2017,12350.0,SH.DTH.IMRT.MA,USA,United States,North America,High income,Not classified
87,2018,12236.0,SH.DTH.IMRT.MA,USA,United States,North America,High income,Not classified
88,2019,12101.0,SH.DTH.IMRT.MA,USA,United States,North America,High income,Not classified
245,2015,160601.0,SH.DTH.IMRT,CHN,China,East Asia & Pacific,Upper middle income,IBRD
246,2016,147325.0,SH.DTH.IMRT,CHN,China,East Asia & Pacific,Upper middle income,IBRD
247,2017,134739.0,SH.DTH.IMRT,CHN,China,East Asia & Pacific,Upper middle income,IBRD
248,2018,123080.0,SH.DTH.IMRT,CHN,China,East Asia & Pacific,Upper middle income,IBRD
249,2019,112595.0,SH.DTH.IMRT,CHN,China,East Asia & Pacific,Upper middle income,IBRD
260,2015,851000.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
261,2016,801578.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
262,2017,756546.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
263,2018,715531.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
264,2019,678728.0,SH.DTH.IMRT,IND,India,South Asia,Lower middle income,IBRD
275,2015,355285.0,SH.DTH.IMRT,PAK,Pakistan,South Asia,Lower middle income,Blend
276,2016,350590.0,SH.DTH.IMRT,PAK,Pakistan,South Asia,Lower middle income,Blend
277,2017,345102.0,SH.DTH.IMRT,PAK,Pakistan,South Asia,Lower middle income,Blend
278,2018,338766.0,SH.DTH.IMRT,PAK,Pakistan,South Asia,Lower middle income,Blend
279,2019,331594.0,SH.DTH.IMRT,PAK,Pakistan,South Asia,Lower middle income,Blend
280,2015,22725.0,SH.DTH.IMRT,USA,United States,North America,High income,Not classified
281,2016,22444.0,SH.DTH.IMRT,USA,United States,North America,High income,Not classified
282,2017,22234.0,SH.DTH.IMRT,USA,United States,North America,High income,Not classified
283,2018,22023.0,SH.DTH.IMRT,USA,United States,North America,High income,Not classified
284,2019,21779.0,SH.DTH.IMRT,USA,United States,North America,High income,Not classified
290,2015,69672.0,SH.DTH.IMRT.FE,CHN,China,East Asia & Pacific,Upper middle income,IBRD
291,2016,64159.0,SH.DTH.IMRT.FE,CHN,China,East Asia & Pacific,Upper middle income,IBRD
292,2017,58777.0,SH.DTH.IMRT.FE,CHN,China,East Asia & Pacific,Upper middle income,IBRD
293,2018,54042.0,SH.DTH.IMRT.FE,CHN,China,East Asia & Pacific,Upper middle income,IBRD
294,2019,49499.0,SH.DTH.IMRT.FE,CHN,China,East Asia & Pacific,Upper middle income,IBRD
305,2015,408725.0,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
306,2016,383982.0,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
307,2017,361415.0,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
308,2018,341012.0,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
309,2019,322490.0,SH.DTH.IMRT.FE,IND,India,South Asia,Lower middle income,IBRD
320,2015,154645.0,SH.DTH.IMRT.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
321,2016,152492.0,SH.DTH.IMRT.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
322,2017,150012.0,SH.DTH.IMRT.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
323,2018,147151.0,SH.DTH.IMRT.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
324,2019,143988.0,SH.DTH.IMRT.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
325,2015,10105.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
326,2016,9979.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
327,2017,9884.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
328,2018,9787.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified
329,2019,9678.0,SH.DTH.IMRT.FE,USA,United States,North America,High income,Not classified

In [ ]:
df_infants_pvt = df_country.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_infants_pvt

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SH.DTH.IMRT,SH.DTH.IMRT.FE,SH.DTH.IMRT.MA
0,2015,CHN,China,East Asia & Pacific,Upper middle income,IBRD,160601.0,69672.0,90929.0
1,2015,IND,India,South Asia,Lower middle income,IBRD,851000.0,408725.0,442275.0
2,2015,PAK,Pakistan,South Asia,Lower middle income,Blend,355285.0,154645.0,200640.0
3,2015,USA,United States,North America,High income,Not classified,22725.0,10105.0,12620.0
4,2016,CHN,China,East Asia & Pacific,Upper middle income,IBRD,147325.0,64159.0,83166.0
5,2016,IND,India,South Asia,Lower middle income,IBRD,801578.0,383982.0,417596.0
6,2016,PAK,Pakistan,South Asia,Lower middle income,Blend,350590.0,152492.0,198098.0
7,2016,USA,United States,North America,High income,Not classified,22444.0,9979.0,12465.0
8,2017,CHN,China,East Asia & Pacific,Upper middle income,IBRD,134739.0,58777.0,75962.0
9,2017,IND,India,South Asia,Lower middle income,IBRD,756546.0,361415.0,395131.0
10,2017,PAK,Pakistan,South Asia,Lower middle income,Blend,345102.0,150012.0,195090.0
11,2017,USA,United States,North America,High income,Not classified,22234.0,9884.0,12350.0
12,2018,CHN,China,East Asia & Pacific,Upper middle income,IBRD,123080.0,54042.0,69038.0
13,2018,IND,India,South Asia,Lower middle income,IBRD,715531.0,341012.0,374519.0
14,2018,PAK,Pakistan,South Asia,Lower middle income,Blend,338766.0,147151.0,191615.0
15,2018,USA,United States,North America,High income,Not classified,22023.0,9787.0,12236.0
16,2019,CHN,China,East Asia & Pacific,Upper middle income,IBRD,112595.0,49499.0,63096.0
17,2019,IND,India,South Asia,Lower middle income,IBRD,678728.0,322490.0,356238.0
18,2019,PAK,Pakistan,South Asia,Lower middle income,Blend,331594.0,143988.0,187606.0
19,2019,USA,United States,North America,High income,Not classified,21779.0,9678.0,12101.0

## Educational attainment in the selected countries

In [ ]:
df_edu =  df_new[df_new["Country Code"].isin(["DEU","KOR","PAK","USA"])]
df_edu

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
16,2015,0.99873,SE.ENR.PRIM.FM.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
17,2016,1.00026,SE.ENR.PRIM.FM.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
18,2017,1.00257,SE.ENR.PRIM.FM.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
19,2018,1.00722,SE.ENR.PRIM.FM.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
20,2019,1.00839,SE.ENR.PRIM.FM.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
...,...,...,...,...,...,...,...,...
383,2015,9.75000,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
384,2016,9.79167,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
385,2017,9.87500,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
386,2018,9.54167,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified
387,2019,9.66667,SG.TIM.UWRK.MA,USA,United States,North America,High income,Not classified

In [ ]:
df_edu_country = df_edu.query("indicator in(['SE.PRM.CUAT.ZS'])")
df_edu_country

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
166,2015,100.000000,SE.PRM.CUAT.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
167,2016,100.000000,SE.PRM.CUAT.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
168,2018,100.000000,SE.PRM.CUAT.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
169,2015,95.506287,SE.PRM.CUAT.ZS,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
170,2016,49.806141,SE.PRM.CUAT.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
171,2017,48.825211,SE.PRM.CUAT.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
172,2018,38.973000,SE.PRM.CUAT.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
173,2019,49.554680,SE.PRM.CUAT.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
174,2015,98.773880,SE.PRM.CUAT.ZS,USA,United States,North America,High income,Not classified
175,2016,98.877113,SE.PRM.CUAT.ZS,USA,United States,North America,High income,Not classified
176,2018,99.031532,SE.PRM.CUAT.ZS,USA,United States,North America,High income,Not classified
177,2020,99.055779,SE.PRM.CUAT.ZS,USA,United States,North America,High income,Not classified

In [ ]:
df_pivot = df_edu_country.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_pivot

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SE.PRM.CUAT.ZS
0,2015,DEU,Germany,Europe & Central Asia,High income,Not classified,100.000000
1,2015,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,95.506287
2,2015,USA,United States,North America,High income,Not classified,98.773880
3,2016,DEU,Germany,Europe & Central Asia,High income,Not classified,100.000000
4,2016,PAK,Pakistan,South Asia,Lower middle income,Blend,49.806141
5,2016,USA,United States,North America,High income,Not classified,98.877113
6,2017,PAK,Pakistan,South Asia,Lower middle income,Blend,48.825211
7,2018,DEU,Germany,Europe & Central Asia,High income,Not classified,100.000000
8,2018,PAK,Pakistan,South Asia,Lower middle income,Blend,38.973000
9,2018,USA,United States,North America,High income,Not classified,99.031532
10,2019,PAK,Pakistan,South Asia,Lower middle income,Blend,49.554680
11,2020,USA,United States,North America,High income,Not classified,99.055779

In [ ]:
fig = px.bar(
    df_pivot.dropna(),
    x = "Year",
    y = "SE.PRM.CUAT.ZS",
    title = "Education enrollment",
    labels = {"Year":"year","SE.PRM.CUAT.ZS":"educational attainment"},
    color = "Country Name",
    animation_frame = "Year",
    log_x=False,
    animation_group = "Country Name"
    #size = "SP.POP.TOTL"
)

#fig.update_traces(textposition = "top center")

fig.show()

## Retirement benefits

In [ ]:
df_retirement = df_new.query("indicator in(['SG.AGE.RTRE.PL.FE','SG.AGE.RTRE.PL.MA'])")
df_retirement

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
89,2019,62.0,SG.AGE.RTRE.PL.FE,FRA,France,Europe & Central Asia,High income,Not classified
90,2020,62.0,SG.AGE.RTRE.PL.FE,FRA,France,Europe & Central Asia,High income,Not classified
91,2019,63.0,SG.AGE.RTRE.PL.FE,DEU,Germany,Europe & Central Asia,High income,Not classified
92,2020,63.0,SG.AGE.RTRE.PL.FE,DEU,Germany,Europe & Central Asia,High income,Not classified
93,2019,50.0,SG.AGE.RTRE.PL.FE,IND,India,South Asia,Lower middle income,IBRD
94,2020,50.0,SG.AGE.RTRE.PL.FE,IND,India,South Asia,Lower middle income,IBRD
95,2019,60.0,SG.AGE.RTRE.PL.FE,JPN,Japan,East Asia & Pacific,High income,Not classified
96,2020,60.0,SG.AGE.RTRE.PL.FE,JPN,Japan,East Asia & Pacific,High income,Not classified
97,2019,60.0,SG.AGE.RTRE.PL.FE,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
98,2020,60.0,SG.AGE.RTRE.PL.FE,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
99,2019,50.0,SG.AGE.RTRE.PL.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
100,2020,50.0,SG.AGE.RTRE.PL.FE,PAK,Pakistan,South Asia,Lower middle income,Blend
101,2019,62.0,SG.AGE.RTRE.PL.FE,USA,United States,North America,High income,Not classified
102,2020,62.0,SG.AGE.RTRE.PL.FE,USA,United States,North America,High income,Not classified
148,2019,62.0,SG.AGE.RTRE.PL.MA,FRA,France,Europe & Central Asia,High income,Not classified
149,2020,62.0,SG.AGE.RTRE.PL.MA,FRA,France,Europe & Central Asia,High income,Not classified
150,2019,63.0,SG.AGE.RTRE.PL.MA,DEU,Germany,Europe & Central Asia,High income,Not classified
151,2020,63.0,SG.AGE.RTRE.PL.MA,DEU,Germany,Europe & Central Asia,High income,Not classified
152,2019,50.0,SG.AGE.RTRE.PL.MA,IND,India,South Asia,Lower middle income,IBRD
153,2020,50.0,SG.AGE.RTRE.PL.MA,IND,India,South Asia,Lower middle income,IBRD
154,2019,60.0,SG.AGE.RTRE.PL.MA,JPN,Japan,East Asia & Pacific,High income,Not classified
155,2020,60.0,SG.AGE.RTRE.PL.MA,JPN,Japan,East Asia & Pacific,High income,Not classified
156,2019,60.0,SG.AGE.RTRE.PL.MA,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
157,2020,60.0,SG.AGE.RTRE.PL.MA,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
158,2019,55.0,SG.AGE.RTRE.PL.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
159,2020,55.0,SG.AGE.RTRE.PL.MA,PAK,Pakistan,South Asia,Lower middle income,Blend
160,2019,62.0,SG.AGE.RTRE.PL.MA,USA,United States,North America,High income,Not classified
161,2020,62.0,SG.AGE.RTRE.PL.MA,USA,United States,North America,High income,Not classified

In [ ]:
df_pivot_ret = df_retirement.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_pivot_ret

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SG.AGE.RTRE.PL.FE,SG.AGE.RTRE.PL.MA
0,2019,DEU,Germany,Europe & Central Asia,High income,Not classified,63.0,63.0
1,2019,FRA,France,Europe & Central Asia,High income,Not classified,62.0,62.0
2,2019,IND,India,South Asia,Lower middle income,IBRD,50.0,50.0
3,2019,JPN,Japan,East Asia & Pacific,High income,Not classified,60.0,60.0
4,2019,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,60.0,60.0
5,2019,PAK,Pakistan,South Asia,Lower middle income,Blend,50.0,55.0
6,2019,USA,United States,North America,High income,Not classified,62.0,62.0
7,2020,DEU,Germany,Europe & Central Asia,High income,Not classified,63.0,63.0
8,2020,FRA,France,Europe & Central Asia,High income,Not classified,62.0,62.0
9,2020,IND,India,South Asia,Lower middle income,IBRD,50.0,50.0
10,2020,JPN,Japan,East Asia & Pacific,High income,Not classified,60.0,60.0
11,2020,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,60.0,60.0
12,2020,PAK,Pakistan,South Asia,Lower middle income,Blend,50.0,55.0
13,2020,USA,United States,North America,High income,Not classified,62.0,62.0

In [ ]:
fig = px.pie(data_frame = df_pivot_ret, values='SG.AGE.RTRE.PL.FE', names='Country Name',title = "retirement benefits for women", hover_name= "Country Name" ,color_discrete_sequence=px.colors.sequential.RdBu)
fig.show()

fig = px.pie(data_frame = df_pivot_ret, values='SG.AGE.RTRE.PL.MA', names='Country Name',title = "retirement benefits for men", hover_name= "Country Name" ,color_discrete_sequence=px.colors.sequential.RdBu)
fig.show()

## Women registering for business

In [ ]:
df_business = df_new.query("indicator in(['SG.BUS.REGT.EQ'])")
df_business

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
178,2015,1.0,SG.BUS.REGT.EQ,AUS,Australia,East Asia & Pacific,High income,Not classified
179,2016,1.0,SG.BUS.REGT.EQ,AUS,Australia,East Asia & Pacific,High income,Not classified
180,2017,1.0,SG.BUS.REGT.EQ,AUS,Australia,East Asia & Pacific,High income,Not classified
181,2018,1.0,SG.BUS.REGT.EQ,AUS,Australia,East Asia & Pacific,High income,Not classified
182,2019,1.0,SG.BUS.REGT.EQ,AUS,Australia,East Asia & Pacific,High income,Not classified
183,2020,1.0,SG.BUS.REGT.EQ,AUS,Australia,East Asia & Pacific,High income,Not classified
184,2015,1.0,SG.BUS.REGT.EQ,CHN,China,East Asia & Pacific,Upper middle income,IBRD
185,2016,1.0,SG.BUS.REGT.EQ,CHN,China,East Asia & Pacific,Upper middle income,IBRD
186,2017,1.0,SG.BUS.REGT.EQ,CHN,China,East Asia & Pacific,Upper middle income,IBRD
187,2018,1.0,SG.BUS.REGT.EQ,CHN,China,East Asia & Pacific,Upper middle income,IBRD
188,2019,1.0,SG.BUS.REGT.EQ,CHN,China,East Asia & Pacific,Upper middle income,IBRD
189,2020,1.0,SG.BUS.REGT.EQ,CHN,China,East Asia & Pacific,Upper middle income,IBRD
190,2015,1.0,SG.BUS.REGT.EQ,FRA,France,Europe & Central Asia,High income,Not classified
191,2016,1.0,SG.BUS.REGT.EQ,FRA,France,Europe & Central Asia,High income,Not classified
192,2017,1.0,SG.BUS.REGT.EQ,FRA,France,Europe & Central Asia,High income,Not classified
193,2018,1.0,SG.BUS.REGT.EQ,FRA,France,Europe & Central Asia,High income,Not classified
194,2019,1.0,SG.BUS.REGT.EQ,FRA,France,Europe & Central Asia,High income,Not classified
195,2020,1.0,SG.BUS.REGT.EQ,FRA,France,Europe & Central Asia,High income,Not classified
196,2015,1.0,SG.BUS.REGT.EQ,DEU,Germany,Europe & Central Asia,High income,Not classified
197,2016,1.0,SG.BUS.REGT.EQ,DEU,Germany,Europe & Central Asia,High income,Not classified
198,2017,1.0,SG.BUS.REGT.EQ,DEU,Germany,Europe & Central Asia,High income,Not classified
199,2018,1.0,SG.BUS.REGT.EQ,DEU,Germany,Europe & Central Asia,High income,Not classified
200,2019,1.0,SG.BUS.REGT.EQ,DEU,Germany,Europe & Central Asia,High income,Not classified
201,2020,1.0,SG.BUS.REGT.EQ,DEU,Germany,Europe & Central Asia,High income,Not classified
202,2015,1.0,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
203,2016,1.0,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
204,2017,1.0,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
205,2018,1.0,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
206,2019,1.0,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
207,2020,1.0,SG.BUS.REGT.EQ,IND,India,South Asia,Lower middle income,IBRD
208,2015,1.0,SG.BUS.REGT.EQ,JPN,Japan,East Asia & Pacific,High income,Not classified
209,2016,1.0,SG.BUS.REGT.EQ,JPN,Japan,East Asia & Pacific,High income,Not classified
210,2017,1.0,SG.BUS.REGT.EQ,JPN,Japan,East Asia & Pacific,High income,Not classified
211,2018,1.0,SG.BUS.REGT.EQ,JPN,Japan,East Asia & Pacific,High income,Not classified
212,2019,1.0,SG.BUS.REGT.EQ,JPN,Japan,East Asia & Pacific,High income,Not classified
213,2020,1.0,SG.BUS.REGT.EQ,JPN,Japan,East Asia & Pacific,High income,Not classified
214,2015,1.0,SG.BUS.REGT.EQ,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
215,2016,1.0,SG.BUS.REGT.EQ,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
216,2017,1.0,SG.BUS.REGT.EQ,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
217,2018,1.0,SG.BUS.REGT.EQ,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
218,2019,1.0,SG.BUS.REGT.EQ,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
219,2020,1.0,SG.BUS.REGT.EQ,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
220,2015,0.0,SG.BUS.REGT.EQ,PAK,Pakistan,South Asia,Lower middle income,Blend
221,2016,0.0,SG.BUS.REGT.EQ,PAK,Pakistan,South Asia,Lower middle income,Blend
222,2017,0.0,SG.BUS.REGT.EQ,PAK,Pakistan,South Asia,Lower middle income,Blend
223,2018,0.0,SG.BUS.REGT.EQ,PAK,Pakistan,South Asia,Lower middle income,Blend
224,2019,0.0,SG.BUS.REGT.EQ,PAK,Pakistan,South Asia,Lower middle income,Blend
225,2020,1.0,SG.BUS.REGT.EQ,PAK,Pakistan,South Asia,Lower middle income,Blend
226,2015,1.0,SG.BUS.REGT.EQ,USA,United States,North America,High income,Not classified
227,2016,1.0,SG.BUS.REGT.EQ,USA,United States,North America,High income,Not classified
228,2017,1.0,SG.BUS.REGT.EQ,USA,United States,North America,High income,Not classified
229,2018,1.0,SG.BUS.REGT.EQ,USA,United States,North America,High income,Not classified
230,2019,1.0,SG.BUS.REGT.EQ,USA,United States,North America,High income,Not classified
231,2020,1.0,SG.BUS.REGT.EQ,USA,United States,North America,High income,Not classified

In [ ]:
df_pivot_business = df_business.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_pivot_business

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SG.BUS.REGT.EQ
0,2015,AUS,Australia,East Asia & Pacific,High income,Not classified,1.0
1,2015,CHN,China,East Asia & Pacific,Upper middle income,IBRD,1.0
2,2015,DEU,Germany,Europe & Central Asia,High income,Not classified,1.0
3,2015,FRA,France,Europe & Central Asia,High income,Not classified,1.0
4,2015,IND,India,South Asia,Lower middle income,IBRD,1.0
5,2015,JPN,Japan,East Asia & Pacific,High income,Not classified,1.0
6,2015,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,1.0
7,2015,PAK,Pakistan,South Asia,Lower middle income,Blend,0.0
8,2015,USA,United States,North America,High income,Not classified,1.0
9,2016,AUS,Australia,East Asia & Pacific,High income,Not classified,1.0
10,2016,CHN,China,East Asia & Pacific,Upper middle income,IBRD,1.0
11,2016,DEU,Germany,Europe & Central Asia,High income,Not classified,1.0
12,2016,FRA,France,Europe & Central Asia,High income,Not classified,1.0
13,2016,IND,India,South Asia,Lower middle income,IBRD,1.0
14,2016,JPN,Japan,East Asia & Pacific,High income,Not classified,1.0
15,2016,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,1.0
16,2016,PAK,Pakistan,South Asia,Lower middle income,Blend,0.0
17,2016,USA,United States,North America,High income,Not classified,1.0
18,2017,AUS,Australia,East Asia & Pacific,High income,Not classified,1.0
19,2017,CHN,China,East Asia & Pacific,Upper middle income,IBRD,1.0
20,2017,DEU,Germany,Europe & Central Asia,High income,Not classified,1.0
21,2017,FRA,France,Europe & Central Asia,High income,Not classified,1.0
22,2017,IND,India,South Asia,Lower middle income,IBRD,1.0
23,2017,JPN,Japan,East Asia & Pacific,High income,Not classified,1.0
24,2017,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,1.0
25,2017,PAK,Pakistan,South Asia,Lower middle income,Blend,0.0
26,2017,USA,United States,North America,High income,Not classified,1.0
27,2018,AUS,Australia,East Asia & Pacific,High income,Not classified,1.0
28,2018,CHN,China,East Asia & Pacific,Upper middle income,IBRD,1.0
29,2018,DEU,Germany,Europe & Central Asia,High income,Not classified,1.0
30,2018,FRA,France,Europe & Central Asia,High income,Not classified,1.0
31,2018,IND,India,South Asia,Lower middle income,IBRD,1.0
32,2018,JPN,Japan,East Asia & Pacific,High income,Not classified,1.0
33,2018,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,1.0
34,2018,PAK,Pakistan,South Asia,Lower middle income,Blend,0.0
35,2018,USA,United States,North America,High income,Not classified,1.0
36,2019,AUS,Australia,East Asia & Pacific,High income,Not classified,1.0
37,2019,CHN,China,East Asia & Pacific,Upper middle income,IBRD,1.0
38,2019,DEU,Germany,Europe & Central Asia,High income,Not classified,1.0
39,2019,FRA,France,Europe & Central Asia,High income,Not classified,1.0
40,2019,IND,India,South Asia,Lower middle income,IBRD,1.0
41,2019,JPN,Japan,East Asia & Pacific,High income,Not classified,1.0
42,2019,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,1.0
43,2019,PAK,Pakistan,South Asia,Lower middle income,Blend,0.0
44,2019,USA,United States,North America,High income,Not classified,1.0
45,2020,AUS,Australia,East Asia & Pacific,High income,Not classified,1.0
46,2020,CHN,China,East Asia & Pacific,Upper middle income,IBRD,1.0
47,2020,DEU,Germany,Europe & Central Asia,High income,Not classified,1.0
48,2020,FRA,France,Europe & Central Asia,High income,Not classified,1.0
49,2020,IND,India,South Asia,Lower middle income,IBRD,1.0
50,2020,JPN,Japan,East Asia & Pacific,High income,Not classified,1.0
51,2020,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,1.0
52,2020,PAK,Pakistan,South Asia,Lower middle income,Blend,1.0
53,2020,USA,United States,North America,High income,Not classified,1.0

In [ ]:
fig = px.bar(
    df_pivot_business.dropna(),
    x = "Year",
    y = "SG.BUS.REGT.EQ",
    title = "Women enrolled in business",
    labels = {"Year":"year","SG.BUS.REGT.EQ":"Women in Business"},
    color = "Country Name",
    animation_frame = "Year",
    log_x=False,
    animation_group = "Country Name"
    #size = "SP.POP.TOTL"
)

#fig.update_traces(textposition = "top center")

fig.show()

# Employement with respect to population

In [ ]:
df_emp = df_new.query("indicator in(['SL.EMP.1524.SP.FE.ZS'])")
df_emp

,Year,value,indicator,Country Code,Country Name,Region,Income Group,Lending Type
330,2015,58.69,SL.EMP.1524.SP.FE.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
331,2016,58.65,SL.EMP.1524.SP.FE.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
332,2017,58.50,SL.EMP.1524.SP.FE.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
333,2018,60.00,SL.EMP.1524.SP.FE.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
334,2019,60.38,SL.EMP.1524.SP.FE.ZS,AUS,Australia,East Asia & Pacific,High income,Not classified
335,2015,41.85,SL.EMP.1524.SP.FE.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
336,2016,40.80,SL.EMP.1524.SP.FE.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
337,2017,39.96,SL.EMP.1524.SP.FE.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
338,2018,39.26,SL.EMP.1524.SP.FE.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
339,2019,38.24,SL.EMP.1524.SP.FE.ZS,CHN,China,East Asia & Pacific,Upper middle income,IBRD
340,2015,26.19,SL.EMP.1524.SP.FE.ZS,FRA,France,Europe & Central Asia,High income,Not classified
341,2016,26.34,SL.EMP.1524.SP.FE.ZS,FRA,France,Europe & Central Asia,High income,Not classified
342,2017,26.86,SL.EMP.1524.SP.FE.ZS,FRA,France,Europe & Central Asia,High income,Not classified
343,2018,27.81,SL.EMP.1524.SP.FE.ZS,FRA,France,Europe & Central Asia,High income,Not classified
344,2019,28.28,SL.EMP.1524.SP.FE.ZS,FRA,France,Europe & Central Asia,High income,Not classified
345,2015,43.66,SL.EMP.1524.SP.FE.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
346,2016,44.24,SL.EMP.1524.SP.FE.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
347,2017,45.40,SL.EMP.1524.SP.FE.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
348,2018,45.41,SL.EMP.1524.SP.FE.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
349,2019,46.26,SL.EMP.1524.SP.FE.ZS,DEU,Germany,Europe & Central Asia,High income,Not classified
350,2015,9.29,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
351,2016,8.67,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
352,2017,8.13,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
353,2018,7.64,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
354,2019,7.42,SL.EMP.1524.SP.FE.ZS,IND,India,South Asia,Lower middle income,IBRD
355,2015,40.79,SL.EMP.1524.SP.FE.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
356,2016,42.57,SL.EMP.1524.SP.FE.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
357,2017,43.01,SL.EMP.1524.SP.FE.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
358,2018,46.68,SL.EMP.1524.SP.FE.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
359,2019,47.94,SL.EMP.1524.SP.FE.ZS,JPN,Japan,East Asia & Pacific,High income,Not classified
360,2015,27.99,SL.EMP.1524.SP.FE.ZS,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
361,2016,28.20,SL.EMP.1524.SP.FE.ZS,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
362,2017,28.17,SL.EMP.1524.SP.FE.ZS,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
363,2018,27.81,SL.EMP.1524.SP.FE.ZS,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
364,2019,27.21,SL.EMP.1524.SP.FE.ZS,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified
365,2015,18.72,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
366,2016,18.13,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
367,2017,17.60,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
368,2018,17.09,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
369,2019,16.98,SL.EMP.1524.SP.FE.ZS,PAK,Pakistan,South Asia,Lower middle income,Blend
370,2015,44.95,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
371,2016,45.79,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
372,2017,47.08,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
373,2018,47.42,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified
374,2019,47.92,SL.EMP.1524.SP.FE.ZS,USA,United States,North America,High income,Not classified

In [ ]:
df_pivot_emp = df_emp.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns ='indicator', values ='value').reset_index()
df_pivot_emp

indicator,Year,Country Code,Country Name,Region,Income Group,Lending Type,SL.EMP.1524.SP.FE.ZS
0,2015,AUS,Australia,East Asia & Pacific,High income,Not classified,58.69
1,2015,CHN,China,East Asia & Pacific,Upper middle income,IBRD,41.85
2,2015,DEU,Germany,Europe & Central Asia,High income,Not classified,43.66
3,2015,FRA,France,Europe & Central Asia,High income,Not classified,26.19
4,2015,IND,India,South Asia,Lower middle income,IBRD,9.29
5,2015,JPN,Japan,East Asia & Pacific,High income,Not classified,40.79
6,2015,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,27.99
7,2015,PAK,Pakistan,South Asia,Lower middle income,Blend,18.72
8,2015,USA,United States,North America,High income,Not classified,44.95
9,2016,AUS,Australia,East Asia & Pacific,High income,Not classified,58.65
10,2016,CHN,China,East Asia & Pacific,Upper middle income,IBRD,40.80
11,2016,DEU,Germany,Europe & Central Asia,High income,Not classified,44.24
12,2016,FRA,France,Europe & Central Asia,High income,Not classified,26.34
13,2016,IND,India,South Asia,Lower middle income,IBRD,8.67
14,2016,JPN,Japan,East Asia & Pacific,High income,Not classified,42.57
15,2016,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,28.20
16,2016,PAK,Pakistan,South Asia,Lower middle income,Blend,18.13
17,2016,USA,United States,North America,High income,Not classified,45.79
18,2017,AUS,Australia,East Asia & Pacific,High income,Not classified,58.50
19,2017,CHN,China,East Asia & Pacific,Upper middle income,IBRD,39.96
20,2017,DEU,Germany,Europe & Central Asia,High income,Not classified,45.40
21,2017,FRA,France,Europe & Central Asia,High income,Not classified,26.86
22,2017,IND,India,South Asia,Lower middle income,IBRD,8.13
23,2017,JPN,Japan,East Asia & Pacific,High income,Not classified,43.01
24,2017,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,28.17
25,2017,PAK,Pakistan,South Asia,Lower middle income,Blend,17.60
26,2017,USA,United States,North America,High income,Not classified,47.08
27,2018,AUS,Australia,East Asia & Pacific,High income,Not classified,60.00
28,2018,CHN,China,East Asia & Pacific,Upper middle income,IBRD,39.26
29,2018,DEU,Germany,Europe & Central Asia,High income,Not classified,45.41
30,2018,FRA,France,Europe & Central Asia,High income,Not classified,27.81
31,2018,IND,India,South Asia,Lower middle income,IBRD,7.64
32,2018,JPN,Japan,East Asia & Pacific,High income,Not classified,46.68
33,2018,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,27.81
34,2018,PAK,Pakistan,South Asia,Lower middle income,Blend,17.09
35,2018,USA,United States,North America,High income,Not classified,47.42
36,2019,AUS,Australia,East Asia & Pacific,High income,Not classified,60.38
37,2019,CHN,China,East Asia & Pacific,Upper middle income,IBRD,38.24
38,2019,DEU,Germany,Europe & Central Asia,High income,Not classified,46.26
39,2019,FRA,France,Europe & Central Asia,High income,Not classified,28.28
40,2019,IND,India,South Asia,Lower middle income,IBRD,7.42
41,2019,JPN,Japan,East Asia & Pacific,High income,Not classified,47.94
42,2019,KOR,"Korea, Rep.",East Asia & Pacific,High income,Not classified,27.21
43,2019,PAK,Pakistan,South Asia,Lower middle income,Blend,16.98
44,2019,USA,United States,North America,High income,Not classified,47.92

In [ ]:
fig = px.scatter(df_pivot_emp, x="Year", y="SL.EMP.1524.SP.FE.ZS", color="Country Name",
                 size='SL.EMP.1524.SP.FE.ZS')
fig.show()